-- ENSPY v2.2.0 PATCH6
-- Per-user notification state + repair attachments generated by academic publications.
CREATE TABLE IF NOT EXISTS notification_user_states (
  notification_id INTEGER NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY(notification_id,user_id)
);
CREATE INDEX IF NOT EXISTS notification_user_states_user_idx ON notification_user_states(user_id,updated_at DESC);

-- Older academic notifications were created without media metadata. Reattach them to the resource file.
UPDATE notifications n
SET media_url=r.file_url,
    media_type=CASE
      WHEN COALESCE(r.mime_type,'') LIKE 'image/%' THEN 'image'
      WHEN COALESCE(r.mime_type,'') LIKE 'video/%' THEN 'video'
      WHEN COALESCE(r.mime_type,'') LIKE 'audio/%' THEN 'audio'
      ELSE 'document'
    END,
    media_name=r.original_name,
    media_mime_type=r.mime_type,
    media_size=r.file_size
FROM academic_resources r
WHERE n.notif_type='document'
  AND n.related_id=r.id
  AND (n.media_url IS NULL OR n.media_name IS NULL OR n.media_mime_type IS NULL);
